### ISSUE TITLE
Minimap out of bounds

### ISSUE THREAD

**Issue by pquerner** [blooblahguy/bdMinimap#2]
Sometimes the minimap is out of bounds. That doesnt happen in doors.
If this is intented, can it be made optional?

![image](https://user-images.githubusercontent.com/4364044/34603568-b297f652-f204-11e7-9d99-ecf389ecff4f.png)

**Comment by gladelynch** [comment]
This is due to the blizzard option Interface -> Display -> Rotate Mini-map. Not sure if I can make a workaround with rectangle minimap, I think you'll have to disable that feature.
