### ISSUE TITLE
Tracking reputation adds a bar to the minimap when AP tracker disabled

### ISSUE THREAD

**Issue by nyliya** [blooblahguy/bdMinimap#5]
As in the title, there is no way to disable the rep bar or the exp bar (I use ElvUI's bar so I would like to turn this one off as it pushes the minimap buttons off my screen)

![screenshot](https://i.gyazo.com/dcce9ce743493e528bc0fa35fc0b5bbb.png)

**Comment by gladelynch** [comment]
Cleaning up issues - this option has existed for a few versions in case you haven't seen it yet
