### ISSUE TITLE
BFA update error

### ISSUE THREAD

**Issue by VaporAPX** [blooblahguy/bdMinimap#6]
Was working fine until the update on beta today, now it gives the following error when you open the world map:

> 251x bdMinimap\core.lua:325: attempt to call global 'GetPlayerMapPosition' (a nil value)
bdMinimap\core.lua:325: in function <bdMinimap\core.lua:323>
Locals:
self = <unnamed> {
 0 = <userdata>
 text = <unnamed> {
 }
}
pX = nil
pY = nil
Nick = nil
cX = nil
cY = nil
cursor = nil
left = nil
bottom = nil
height = nil
width = nil
scale = nil
(*temporary) = nil
(*temporary) = "player"
(*temporary) = "attempt to call global 'GetPlayerMapPosition' (a nil value)"

**Comment by SeeTwoDev** [comment]
I have the same issue :/

**Comment by VaporAPX** [comment]
It's fixable by opening the core.lua file and going to line 325 and simply removing ("player") from the end of "GetPlayerMapPosition".

**Comment by gladelynch** [comment]
Just cleaning up issues - this is resolved
