### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Solence1** [blooblahguy/bdMinimap#7]
Hey i love your addon and would like to make some suggestions. I know you got your hands full for bfa updates already but i hope you can consider my suggestions.

ok so first: i would like to be able to hide the xpbar below the minimap completely

and second: i'd like an option to change the anchor of the minimap buttons so they dont move out of the frame when i put my minimap to the bottomright corner

I could not find anything suggesting those changes are possible. I also could life with a lua fix that i have to reaply every update.

much love

**Comment by gladelynch** [comment]
Hey - just cleaning up issues. Both of these options should already be in the addon
